#!/bin/bash

cp badkernel.img badkernel.img2
../src/shush-kernel badkernel.img
res=$?
mv badkernel.img2 badkernel.img


if [ "$res" == "0" ]; then
	echo "shush-kernel succeeded on a bad kernel image!"
	exit 1
fi

cp goodkernel.img goodkernel.img2
../src/shush-kernel goodkernel.img

res=$?

if ! [ "$res" == "0" ]; then
	echo "shush-kernel failed on a good kernel image!"
	mv goodkernel.img2 goodkernel.img
	exit 1
fi

diff goodkernel.img goodkernel.result
res=$?
mv goodkernel.img2 goodkernel.img


if ! [ "$res" == "0"]; then
	echo "shush-kernel failed to create the desired kernel image!"
	exit 1
fi

echo "shush-kernel tests succeeded!"
